// AUTO-GENERATED by scripts/parse-drip.mjs from ../files/drip-email-copy.md
// Do not edit by hand — re-run the parser after changing the copy.
// Merge tags in bodies: {{first_name}} {{agent_name}} {{agent_phone}}
// {{agent_email}} {{brokerage}} {{property_address}} {{property_price}}
// Rendered by renderEmail() in src/lib/email.ts

export interface SeedSequence {
  tier: 'HOT' | 'WARM' | 'COLD';
  dayOffset: number;
  subject: string;
  body: string;
}

export const EMAIL_SEQUENCES: SeedSequence[] = [
  {
    "tier": "HOT",
    "dayOffset": 0,
    "subject": "Great meeting you at {{property_address}}",
    "body": "Hey {{first_name}},\n\nThanks for stopping by {{property_address}} today — I loved showing it off.\n\nQuick question so I can point you at the right things: are you pre-approved yet, and roughly when are you hoping to move? A one-line reply is plenty (\"yes, 3 months\").\n\nIf {{property_address}} caught your eye, I'd move fast — homes in this area aren't sitting long.\n\n— {{agent_name}}\n{{agent_phone}} · {{brokerage}}"
  },
  {
    "tier": "HOT",
    "dayOffset": 1,
    "subject": "Still thinking about {{property_address}}?",
    "body": "Hey {{first_name}},\n\nStill thinking about {{property_address}}? A couple of quick things:\n\n- The comparable homes nearby sold for {{property_price}} and up — it's priced right.\n- If you want a second look, I can get you in this week before the weekend rush.\n\nWant me to set that up? Just reply \"yes\" and I'll send you two time slots.\n\n— {{agent_name}}\n{{agent_phone}}"
  },
  {
    "tier": "HOT",
    "dayOffset": 3,
    "subject": "3 homes like {{property_address}} (priced {{property_price}}–{{property_price}})",
    "body": "Hey {{first_name}},\n\nSince you liked {{property_address}}, I pulled three similar homes that just hit the market in the same price range. Want the list? Reply \"send them\" and I'll forward it with my honest take on each one.\n\nNo obligation — I just know good ones move fast in this market.\n\n— {{agent_name}}\n{{agent_phone}}"
  },
  {
    "tier": "HOT",
    "dayOffset": 7,
    "subject": "Quick check-in, {{first_name}}",
    "body": "Hey {{first_name}},\n\nWanted to check in personally — where did you land on {{property_address}}? Still in the running, or should I keep hunting for something better?\n\nEither way, 10 minutes on the phone and I can sharpen the search so you're only seeing homes worth your time. When's a good window this week?\n\n— {{agent_name}}\n{{agent_phone}}"
  },
  {
    "tier": "HOT",
    "dayOffset": 12,
    "subject": "Just sold a home near {{property_address}} — here's what it means for you",
    "body": "Hey {{first_name}},\n\nQuick market note: a comparable home near {{property_address}} just sold over asking with multiple offers. Demand in this pocket is real right now.\n\nIf you're serious about buying in the next few months, the worst strategy is waiting and hoping. Want me to run the numbers on what your monthly would look like at current rates? Takes me 5 minutes.\n\n— {{agent_name}}\n{{agent_phone}}"
  },
  {
    "tier": "HOT",
    "dayOffset": 20,
    "subject": "New listings this week worth a look",
    "body": "Hey {{first_name}},\n\nTwo new listings dropped this week that fit what you told me at the open house. I haven't sent these to anyone else yet.\n\nReply \"show me\" and I'll send photos, pricing, and my honest opinion — including anything I'd flag as a red flag.\n\n— {{agent_name}}\n{{agent_phone}}"
  },
  {
    "tier": "HOT",
    "dayOffset": 30,
    "subject": "Should I keep you on my list, {{first_name}}?",
    "body": "Hey {{first_name}},\n\nIt's been about a month since the open house at {{property_address}}. No pressure at all — just want to know where things stand:\n\n1. Still looking → I'll keep sending you first dibs on new listings.\n2. Paused for now → I'll check back in a couple months.\n3. Found something → congrats! I'd love to hear about it.\n\nHit reply with 1, 2, or 3?\n\n— {{agent_name}}\n{{agent_phone}}"
  },
  {
    "tier": "WARM",
    "dayOffset": 0,
    "subject": "Thanks for visiting {{property_address}}",
    "body": "Hey {{first_name}},\n\nThanks for coming through {{property_address}}! I'll keep you in the loop on this one — and anything similar that comes up in the area.\n\nIf you ever want a private walkthrough or just have questions about the process, I'm an easy text away.\n\n— {{agent_name}}\n{{agent_phone}} · {{brokerage}}"
  },
  {
    "tier": "WARM",
    "dayOffset": 3,
    "subject": "Buying in the next 6–12 months? Read this first",
    "body": "Hey {{first_name}},\n\nSince you mentioned you're still a few months out, here's the single most useful thing you can do now: get pre-approved early. It costs nothing, takes about 20 minutes, and it makes your offer 10x stronger when the right home shows up.\n\nI work with a couple of great lenders who won't waste your time. Want an intro? Just reply \"yes.\"\n\n— {{agent_name}}\n{{agent_phone}}"
  },
  {
    "tier": "WARM",
    "dayOffset": 7,
    "subject": "The neighborhood around {{property_address}}, honestly",
    "body": "Hey {{first_name}},\n\nYou toured {{property_address}}, so here's my honest take on the area: walkability is great, the schools are solid, and prices have been climbing steadily for 3 years. The one thing to know — parking can be tight on weekends.\n\nIf you're curious about any other neighborhoods, tell me what matters to you (commute, schools, nightlife) and I'll send my top 3 picks.\n\n— {{agent_name}}\n{{agent_phone}}"
  },
  {
    "tier": "WARM",
    "dayOffset": 14,
    "subject": "Your 2-minute market update",
    "body": "Hey {{first_name}},\n\nQuick snapshot of what's happening out there:\n\n- Inventory is up slightly from last month — more options for you.\n- Rates have been holding steady, which is good news.\n- Well-priced homes are still moving in under 2 weeks.\n\nBottom line: no rush, but stay ready. When the right one appears, you'll want to move.\n\n— {{agent_name}}\n{{agent_phone}}"
  },
  {
    "tier": "WARM",
    "dayOffset": 21,
    "subject": "4 homes you might like (based on {{property_address}})",
    "body": "Hey {{first_name}},\n\nI hand-picked 4 listings that match what you seemed to like about {{property_address}} — similar style, similar price point, all currently available.\n\nReply \"send the list\" and I'll forward it over with my notes on each.\n\n— {{agent_name}}\n{{agent_phone}}"
  },
  {
    "tier": "WARM",
    "dayOffset": 30,
    "subject": "One question, {{first_name}}",
    "body": "Hey {{first_name}},\n\nIt's been a month since you visited {{property_address}} — curious where your head is at. Still casually looking, getting serious, or on pause?\n\nWhatever the answer, no judgment. It just helps me send you the right stuff instead of noise.\n\n— {{agent_name}}\n{{agent_phone}}"
  },
  {
    "tier": "WARM",
    "dayOffset": 45,
    "subject": "You're invited — open houses this weekend",
    "body": "Hey {{first_name}},\n\nI'm hosting two open houses this weekend and I'd love for you to stop by — no appointment needed:\n\n- Saturday 12–2pm: [address 1]\n- Sunday 1–3pm: [address 2]\n\nBoth are in the same general area as {{property_address}}. Come say hi — I'll have the coffee on.\n\n— {{agent_name}}\n{{agent_phone}}"
  },
  {
    "tier": "WARM",
    "dayOffset": 60,
    "subject": "Still here when you're ready, {{first_name}}",
    "body": "Hey {{first_name}},\n\nTwo months since the open house — just wanted you to know I'm still here whenever the timing is right. Markets shift, life shifts, and when you're ready to get serious, I'll make sure you see the best options first.\n\nIn the meantime, I'll keep the updates useful and infrequent. Reply anytime — I read everything myself.\n\n— {{agent_name}}\n{{agent_phone}}"
  },
  {
    "tier": "COLD",
    "dayOffset": 0,
    "subject": "Thanks for stopping by {{property_address}}",
    "body": "Hey {{first_name}},\n\nThanks for visiting {{property_address}}! I'll keep you posted if anything interesting comes up in the area.\n\nNo pressure, no spam — just useful updates now and then.\n\n— {{agent_name}}\n{{brokerage}}"
  },
  {
    "tier": "COLD",
    "dayOffset": 14,
    "subject": "What's actually happening in the market (no hype)",
    "body": "Hey {{first_name}},\n\nQuick, hype-free market note: prices in the area around {{property_address}} have been steady, inventory is normal for this time of year, and rates are doing what rates do.\n\nI'll keep sending these short updates now and then. If you ever want the full picture on a specific home, just ask.\n\n— {{agent_name}}"
  },
  {
    "tier": "COLD",
    "dayOffset": 30,
    "subject": "5 things to check before you ever tour a home",
    "body": "Hey {{first_name}},\n\nWhether you buy in 3 months or 3 years, this list will save you headaches:\n\n1. Get pre-approved before you fall in love with anything.\n2. Drive the neighborhood at night, not just during the open house.\n3. Ask about the age of the roof, furnace, and windows.\n4. Check the property taxes — they vary more than you'd think.\n5. Bring a tape measure. Seriously.\n\nFile it away for when the time comes.\n\n— {{agent_name}}"
  },
  {
    "tier": "COLD",
    "dayOffset": 60,
    "subject": "Just checking in, {{first_name}}",
    "body": "Hey {{first_name}},\n\nTwo months since {{property_address}} — hope things are going well. Any movement on the home front, or still in the \"someday\" phase?\n\nEither way, I'm here when you need me.\n\n— {{agent_name}}\n{{agent_phone}}"
  },
  {
    "tier": "COLD",
    "dayOffset": 120,
    "subject": "The market, 4 months later",
    "body": "Hey {{first_name}},\n\nIt's been a while — here's where things stand compared to when you toured {{property_address}}:\n\n- New listings are still coming, but the best ones move fast.\n- If buying is on your 2026/2027 radar, now's a good time to start watching seriously.\n\nWant me to set up a saved search so new matches land in your inbox automatically? Reply \"set it up.\"\n\n— {{agent_name}}"
  },
  {
    "tier": "COLD",
    "dayOffset": 180,
    "subject": "Last check-in — still want these updates, {{first_name}}?",
    "body": "Hey {{first_name}},\n\nSix months since we met at {{property_address}}. I'll keep this simple:\n\n- Still interested in buying someday? Reply \"keep me posted\" and I'll stay in touch with the good stuff.\n- Not anymore? Reply \"all set\" and I'll take you off the list, no hard feelings.\n\nEither way, it was great meeting you.\n\n— {{agent_name}}\n{{agent_phone}}"
  }
];
