// One-off helper: parses the drip-copy markdown Sam approved and generates
// prisma/seed-data.ts. Run: node scripts/parse-drip.mjs
// Kept in the repo so the seed can be regenerated if the copy ever changes.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const md = readFileSync(
  join(root, '..', 'files', 'drip-email-copy.md'),
  'utf8'
);

const lines = md.split('\n');
const emails = [];
let current = null;

const headerRe = /^###\s+(Hot|Warm|Cold)\s+#\d+\s+[—–-]\s+Day\s+(\d+)/i;
const subjectRe = /^\*\*Subject:\*\*\s*(.+?)\s*$/;

for (const line of lines) {
  const h = line.match(headerRe);
  if (h) {
    if (current) emails.push(current);
    current = {
      tier: h[1].toUpperCase(),
      dayOffset: Number(h[2]),
      subject: '',
      bodyLines: [],
    };
    continue;
  }
  if (!current) continue;
  // Stop the body at the review-checklist section or horizontal rules.
  if (/^##\s+/.test(line) || /^\s*---\s*$/.test(line)) {
    emails.push(current);
    current = null;
    continue;
  }
  const s = line.match(subjectRe);
  if (s) {
    current.subject = s[1];
    continue;
  }
  current.bodyLines.push(line);
}
if (current) emails.push(current);

function cleanBody(rawLines) {
  // Drop leading/trailing blank lines, strip **bold** markers, collapse runs.
  let text = rawLines.join('\n').replace(/\*\*/g, '').trim();
  text = text.replace(/\n{3,}/g, '\n\n');
  return text;
}

const data = emails.map((e) => ({
  tier: e.tier,
  dayOffset: e.dayOffset,
  subject: e.subject,
  body: cleanBody(e.bodyLines),
}));

// Sanity checks — fail loudly rather than seeding garbage.
if (data.length !== 21) {
  throw new Error(`Expected 21 emails, parsed ${data.length}`);
}
for (const e of data) {
  if (!e.subject || !e.body) {
    throw new Error(`Missing subject/body for ${e.tier} day ${e.dayOffset}`);
  }
}

const out =
  `// AUTO-GENERATED by scripts/parse-drip.mjs from ../files/drip-email-copy.md\n` +
  `// Do not edit by hand — re-run the parser after changing the copy.\n` +
  `// Merge tags in bodies: {{first_name}} {{agent_name}} {{agent_phone}}\n` +
  `// {{agent_email}} {{brokerage}} {{property_address}} {{property_price}}\n` +
  `// Rendered by renderEmail() in src/lib/email.ts\n\n` +
  `export interface SeedSequence {\n` +
  `  tier: 'HOT' | 'WARM' | 'COLD';\n` +
  `  dayOffset: number;\n` +
  `  subject: string;\n` +
  `  body: string;\n` +
  `}\n\n` +
  `export const EMAIL_SEQUENCES: SeedSequence[] = ${JSON.stringify(data, null, 2)};\n`;

writeFileSync(join(root, 'prisma', 'seed-data.ts'), out);
console.log(`Wrote ${data.length} sequences to prisma/seed-data.ts`);
for (const e of data) console.log(`  ${e.tier} day ${e.dayOffset}: ${e.subject}`);
